/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as CapaRouteImport } from './routes/capa'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as HaccpRouteImport } from './routes/haccp'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PrpRouteImport } from './routes/prp'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as TraceabilityRouteImport } from './routes/traceability'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const CapaRoute = CapaRouteImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const HaccpRoute = HaccpRouteImport.update({
  id: '/haccp',
  path: '/haccp',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PrpRoute = PrpRouteImport.update({
  id: '/prp',
  path: '/prp',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/capa': typeof CapaRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/equipment': typeof EquipmentRoute
  '/haccp': typeof HaccpRoute
  '/inventory': typeof InventoryRoute
  '/organization': typeof OrganizationRoute
  '/prp': typeof PrpRoute
  '/purchasing': typeof PurchasingRoute
  '/traceability': typeof TraceabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/capa': typeof CapaRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/equipment': typeof EquipmentRoute
  '/haccp': typeof HaccpRoute
  '/inventory': typeof InventoryRoute
  '/organization': typeof OrganizationRoute
  '/prp': typeof PrpRoute
  '/purchasing': typeof PurchasingRoute
  '/traceability': typeof TraceabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/capa': typeof CapaRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/equipment': typeof EquipmentRoute
  '/haccp': typeof HaccpRoute
  '/inventory': typeof InventoryRoute
  '/organization': typeof OrganizationRoute
  '/prp': typeof PrpRoute
  '/purchasing': typeof PurchasingRoute
  '/traceability': typeof TraceabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/capa'
    | '/dashboard'
    | '/documents'
    | '/equipment'
    | '/haccp'
    | '/inventory'
    | '/organization'
    | '/prp'
    | '/purchasing'
    | '/traceability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audits'
    | '/capa'
    | '/dashboard'
    | '/documents'
    | '/equipment'
    | '/haccp'
    | '/inventory'
    | '/organization'
    | '/prp'
    | '/purchasing'
    | '/traceability'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/capa'
    | '/dashboard'
    | '/documents'
    | '/equipment'
    | '/haccp'
    | '/inventory'
    | '/organization'
    | '/prp'
    | '/purchasing'
    | '/traceability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRoute
  CapaRoute: typeof CapaRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EquipmentRoute: typeof EquipmentRoute
  HaccpRoute: typeof HaccpRoute
  InventoryRoute: typeof InventoryRoute
  OrganizationRoute: typeof OrganizationRoute
  PrpRoute: typeof PrpRoute
  PurchasingRoute: typeof PurchasingRoute
  TraceabilityRoute: typeof TraceabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capa': {
      id: '/capa'
      path: '/capa'
      fullPath: '/capa'
      preLoaderRoute: typeof CapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haccp': {
      id: '/haccp'
      path: '/haccp'
      fullPath: '/haccp'
      preLoaderRoute: typeof HaccpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prp': {
      id: '/prp'
      path: '/prp'
      fullPath: '/prp'
      preLoaderRoute: typeof PrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRoute,
  CapaRoute: CapaRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EquipmentRoute: EquipmentRoute,
  HaccpRoute: HaccpRoute,
  InventoryRoute: InventoryRoute,
  OrganizationRoute: OrganizationRoute,
  PrpRoute: PrpRoute,
  PurchasingRoute: PurchasingRoute,
  TraceabilityRoute: TraceabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
